# Generated by Django 2.1.3 on 2019-05-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('postdate', models.DateField(blank=True, null=True, verbose_name='Post date')),
                ('description', models.TextField(help_text='Type your post here', max_length=3000)),
            ],
            options={
                'ordering': ['-postdate'],
            },
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(help_text='Enter blogger biography', max_length=500)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Born')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please select the language(s) your post is written in', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a theme for your post', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogger'),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ManyToManyField(help_text='Select the content language(s)', to='blog.Language'),
        ),
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.ManyToManyField(help_text='Please select a theme for your post', to='blog.Theme'),
        ),
    ]
