# Generated by Django 2.1.3 on 2019-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190501_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postdate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Post date'),
        ),
    ]
