# Generated by Django 2.1.3 on 2019-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Posted'),
        ),
    ]
